name: CI

on:
  schedule:
    - cron: "0 */4 * * *"
  push:
    branches: ["master", "**"]
  pull_request:
    branches: ["master", "**"]
  workflow_dispatch:

jobs:
  deno:
    runs-on: ubuntu-latest
    name: Lint & Build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Setup pnpm@v9
        run: npm i -g pnpm@9.0.0; pnpm -v

      - name: Install Dependencies
        run: pnpm i

      - name: Deno Format
        run: deno fmt

      - name: Build the Project
        run: |
          deno task build | tee build.log
        continue-on-error: true

      - name: Upload Build Log to Summary
        if: always()
        run: |
          echo '# Build Log Output ' >> $GITHUB_STEP_SUMMARY
          cat build.log >> $GITHUB_STEP_SUMMARY